---
applications:
- instances: 1
  buildpack: binary_buildpack
  command: ./stress-app
  memory: 4096M
  disk_quota: 100M
  env:
    LOGS_PER_SECOND: 10
    REQUESTS_PER_SECOND: .07
    CPU_BURNS_PER_SECOND: 1000
    MEM_BURNS_PER_SECOND: 1000
